#!/bin/bash

DOCKERIMAGE=rucio/rucio-server:release-1.16.3
#RUCIOETCHOST=/home/james.clark/ligo-rucio/server/etc # bind this to /opt/rucio/etc
RUCIOETCHOST=/home/jclark/Projects/ligo-rucio/server/etc # bind this to /opt/rucio/etc

docker run --privileged \
    --name rucio-server \
    -v ${RUCIOETCHOST}:/opt/rucio/etc \
    -v /etc/hostname:/etc/hostname \
    -v /var/log/httpd:/var/log/httpd \
    -v /etc/grid-security/hostcert.pem:/etc/grid-security/hostcert.pem \
    -v /etc/grid-security/hostkey.pem:/etc/grid-security/hostkey.pem \
    -v /sys/fs/cgroup:/sys/fs/cgroup:ro \
    -v /etc/grid-security:/etc/grid-security \
    -v /etc/pki:/etc/pki \
    -d -p 443:443 ${DOCKERIMAGE}

