#!/bin/bash

#DOCKERIMAGE=gitlab-registry.cern.ch/rucio01/rucio/mysql_server 
DOCKERIMAGE=rucio/rucio-server:release-1.16.1
#RUCIOETCHOST=/home/james.clark/ligo-rucio/server/etc # bind this to /opt/rucio/etc
RUCIOETCHOST=/opt/rucio/etc # bind this to /opt/rucio/etc
#RUCIOETCHOST=/home/james.clark/etc # bind this to /opt/rucio/etc

docker run --privileged \
    --name rucio-server \
    -v ${RUCIOETCHOST}:/opt/rucio/etc \
    -v /home:/home \
    -v /etc/hostname:/etc/hostname \
    -v /var/log/httpd:/var/log/httpd \
    -v /etc/httpd/x509-certs/rucio.ligo.caltech.edu.pem \
    -v /etc/httpd/x509-certs/rucio.ligo.caltech.edu.key \
    -v /sys/fs/cgroup:/sys/fs/cgroup:ro \
    -v /etc/grid-security:/etc/grid-security \
    -v /etc/pki:/etc/pki \
    -d -p 443:443 ${DOCKERIMAGE}

