#!/bin/sh -e

export OMP_NUM_THREADS=100

gwrucio_register_data -p ER10-HOFT_C02.yml \
	--verbose --lifetime 3600 \
    --dry-run \
	add-files $(< deptest.txt) \
    --pset H-H1_HOFT_C02
#    --pset H1_ER10_HOFT_C02
#	add-files $(< ER10-H1_HOFT_C02.txt) \
