#!/bin/sh -e

# Get ascii list of frames with e.g., ls -d -1 $PWD/**/*gwf.  Ideally use DiskCache.
# Better yet: find $PWD -type f -name *gwf
ligo_register_data \
    --rse LIGO-CIT-ARCHIVE \
    --scope ER8 \
    --debug --verbose \
  /hdfs/frames/ER8/hoft/L1/L-L1_HOFT_C00-11250/L-L1_HOFT_C00-1125011456-4096.gwf

