#!/bin/sh -e

# Hack to build file list: find FRAMEPATH -type f -name *gwf
ligo_register_data -p H-H1_HOFT_C00-11643-files.yaml \
	--dry-run --verbose \
	add-files --lifetime 600 \
  /cvmfs/oasis.opensciencegrid.org/ligo/frames/ER10/hoft/H1/H-H1_HOFT_C00-11643/H-H1_HOFT_C00-1164353536-4096.gwf \
  /cvmfs/oasis.opensciencegrid.org/ligo/frames/ER10/hoft/H1/H-H1_HOFT_C00-11643/H-H1_HOFT_C00-1164369920-4096.gwf 
#	--file-list H-H1_HOFT_C00-11643.txt
