#!/bin/sh -x
./rse_distance LIGO-CIT LIGO-CIT-ARCHIVE
./rse_distance LIGO-CIT LIGO-CIT-HDFS
./rse_distance LIGO-CIT LIGO-WA-HDFS
./rse_distance LIGO-CIT-ARCHIVE LIGO-CIT
./rse_distance LIGO-CIT-ARCHIVE LIGO-CIT-HDFS
./rse_distance LIGO-CIT-ARCHIVE LIGO-WA-HDFS
./rse_distance LIGO-CIT-HDFS LIGO-CIT
./rse_distance LIGO-CIT-HDFS LIGO-CIT-ARCHIVE
./rse_distance LIGO-CIT-HDFS LIGO-WA-HDFS
./rse_distance LIGO-WA-HDFS LIGO-CIT
./rse_distance LIGO-WA-HDFS LIGO-CIT-ARCHIVE
./rse_distance LIGO-WA-HDFS LIGO-CIT-HDFS

