#!/bin/sh -e

# LIGO-CIT
rse="LIGO-CIT"
rucio-admin rse set-attribute --rse ${rse} --key mountpoint --value archive
rucio-admin rse set-attribute --rse ${rse} --key type --value TEST
rucio-admin rse set-attribute --rse ${rse} --key site --value CIT

# LIGO-CIT-HDFS
rse="LIGO-CIT-HDFS"
rucio-admin rse set-attribute --rse ${rse} --key mountpoint --value hdfs
rucio-admin rse set-attribute --rse ${rse} --key type --value TEST
rucio-admin rse set-attribute --rse ${rse} --key site --value CIT


# LIGO-CIT-ARCHIVE
rse="LIGO-CIT-ARCHIVE"
rucio-admin rse set-attribute --rse ${rse} --key mountpoint --key hdfs --value ARCHIVE
rucio-admin rse set-attribute --rse ${rse} --key type --value ARCHIVE
rucio-admin rse set-attribute --rse ${rse} --key site --value CIT

# LIGO-WA
rse="LIGO-WA"
rucio-admin rse set-attribute --rse ${rse} --key mountpoint --value archive
rucio-admin rse set-attribute --rse ${rse} --key type --value TEST
rucio-admin rse set-attribute --rse ${rse} --key site --value LHO

# LIGO-WA-HDFS
rse="LIGO-WA-HDFS"
rucio-admin rse set-attribute --rse ${rse} --key mountpoint --value hdfs
rucio-admin rse set-attribute --rse ${rse} --key type --value TEST
rucio-admin rse set-attribute --rse ${rse} --key site --value LHO
