#!/bin/sh -e

OMP_NUM_THREADS=100
ligo_register_data -p HL-ER10-HOFT_CO2.yml \
  --dry-run --verbose --lifetime 600 daemon \
  /home/jclark/Projects/ligo-rucio/diskcache/frame_cache_dump

# ligo_register_data -p HL-ER10-HOFT_CO2.yml --dry-run --verbose --lifetime 600 daemon /home/jclark/Projects/ligo-rucio/diskcache/frame_cache_dump 
