#!/bin/bash -e

rucio -v upload \
    --summary \
    --scope postO1 --rse LIGO-CIT \
    --protocol gsiftp \
    --pfn /archive/rucio/postO1/hoft/H1/H-H1_HOFT_C00-11631/H-H1_HOFT_C00-1163100160-4096.gwf \
    ER13:H-H1_HOFT_C00-1163100160-4096.gwf
